import React from 'react';
import {number, select, text} from '@storybook/addon-knobs';

import { createMetadata } from '../../../utils/storybook';

import { IconsItem } from './Item/Icons-Item';
import mdx from './Icon.docs.mdx';

const defaultKnobs = () => ({
  size: select('size', ['xxs', 'xs', 's', 'm', 'l'], 'l'),
  color: text('color', '#293468'),
  customSize: number('customSize', null)
});

const header = [
  'bell',
  'bell-off',
  'help-circle',
  'settings-dev',
  'sign-out',
  'sign-up',
  'user',
  'users',
  'user-add',
  'user-delete'
];

const functionalBar = [
  'bullet-list-search',
  'calculator',
  'calculator-check',
  'color',
  'colorpicker',
  'eye',
  'eye-invisible',
  'file-search',
  'filter',
  'filter-check',
  'folder-search',
  'full-screen',
  'full-screen-exit',
  'group',
  'group-check',
  'history',
  'plus-s-double',
  'plus-s-double-check',
  'refresh',
  'save',
  'search',
  'search-check',
  'search-in',
  'search-out',
  'sort-down',
  'sort-check',
  'sort-up',
  'text-color',
  'ungroup'
];

const diagrams = [
  'bar-chart-h',
  'bar-chart-v',
  'bar-chart-v-check',
  'data-histogram',
  'data-line',
  'line-chart',
  'pie-chart'
];

const arrows = [
  'arrow-backward',
  'arrow-forward',
  'arrow-left-c',
  'arrow-right-c',
  'arrow-down-c',
  'arrow-up-c',
  'arrow-swap',
  'arrow-left',
  'arrow-right',
  'arrow-up',
  'arrow-down',
  'arrow-move',
  'arrow-v-left',
  'arrow-v-right',
  'arrows-h',
  'arrows-v',
  'caret-left',
  'caret-right',
  'caret-up',
  'caret-down',
  'caret-left-s',
  'caret-right-s',
  'caret-up-s',
  'caret-down-s',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'chevron-down',
  'chevron-left-c',
  'chevron-right-c',
  'chevron-up-c',
  'chevron-down-c'
];

const allIcons = [
  "action-menu",
  "aggregate",
  "ancore",
  "apps",
  "archive",
  "arrow-backward",
  "arrow-forward",
  "arrow-left-c",
  "arrow-right-c",
  "arrow-down-c",
  "arrow-up-c",
  "arrow-swap",
  "arrow-left",
  "arrow-right",
  "arrow-up",
  "arrow-down",
  "arrow-move",
  "arrow-v-left",
  "arrow-v-right",
  "arrows-h",
  "arrows-v",
  "asteriks",
  "backward",
  "bank",
  "bar-chart-h",
  "bar-chart-v",
  "bar-chart-v-check",
  "base",
  "base-server",
  "big-grid",
  "stroke-grid",
  "bell",
  "bell-off",
  "binokulars",
  "block",
  "book",
  "book-download",
  "book-finance",
  "book-formula",
  "book-upload",
  "book-warning",
  "branch",
  "breifcase",
  "bring-to-front",
  "bug",
  "bullet-list",
  "bullet-list-search",
  "building",
  "calculator",
  "calculator-check",
  "calendar",
  "calendar-nule",
  "calendar-check",
  "calendar-day",
  "calendar-delete",
  "calendar-minus",
  "calendar-plus",
  "calendar-recur",
  "camera",
  "caret-left",
  "caret-right",
  "caret-up",
  "caret-down",
  "caret-left-s",
  "caret-right-s",
  "caret-up-s",
  "caret-down-s",
  "chat",
  "chat-question",
  "chat-dialog",
  "chat-help",
  "chat-off",
  "chat-warning",
  "check",
  "check-double",
  "check-full",
  "check-c",
  "check-c-filled",
  "check-on",
  "check-status",
  "chevron-left",
  "chevron-right",
  "chevron-up",
  "chevron-down",
  "chevron-left-c",
  "chevron-right-c",
  "chevron-up-c",
  "chevron-down-c",
  "cicle",
  "circle",
  "circle-o",
  "clip",
  "clipboard",
  "clock",
  "close",
  "close-c",
  "close-menu",
  "cloud",
  "cloud-upload",
  "cloud-download",
  "cloud-server",
  "code",
  "code-html",
  "color",
  "colorpicker",
  "collapse",
  "comment",
  "comment-chat",
  "compose",
  "connect",
  "contact",
  "control",
  "cookies",
  "copy",
  "cub",
  "cut",
  "dark-theme",
  "data-histogram",
  "data-line",
  "date-scatter",
  "delete",
  "design",
  "desktop",
  "developer-board",
  "dictionary",
  "directory",
  "divider",
  "disconnect",
  "display-only",
  "doc-top",
  "doc-bottom",
  "doc-left",
  "doc-right",
  "doc-left-close",
  "doc-right-close",
  "document",
  "documents",
  "dotted",
  "double-down",
  "double-up",
  "double-left",
  "double-right",
  "double-reply",
  "down",
  "download",
  "drag",
  "drag-and-drop",
  "drawer",
  "dublicate",
  "edit",
  "eject",
  "ellipsis-h",
  "ellipsis-v",
  "email",
  "envelope-email-s",
  "erase",
  "eur",
  "eye",
  "eye-invisible",
  "eye-inv-check",
  "export",
  "external-link",
  "external-link-s",
  "fast-backward",
  "fast-forward",
  "fax",
  "file",
  "file-ai",
  "file-csv",
  "file-delete",
  "file-download",
  "file-eps",
  "file-minus",
  "file-pdf",
  "file-png",
  "file-plus",
  "file-ppt",
  "file-search",
  "file-svg",
  "file-text",
  "file-upload",
  "file-xml",
  "file-zip",
  "file-xlsx",
  "file-doc",
  "files",
  "fill",
  "filter",
  "filter-check",
  "flag",
  "flash",
  "folder",
  "folder-delete",
  "folder-download",
  "folder-minus",
  "folder-public",
  "folder-search",
  "folder-upload",
  "folder-zip",
  "folder-plus",
  "folder-open",
  "form",
  "fort",
  "forward",
  "full-screen",
  "full-screen-exit",
  "function-field",
  "gbp",
  "gift",
  "globe",
  "graduation-cap",
  "grid",
  "group",
  "group-check",
  "hdd",
  "heart",
  "history",
  "home",
  "hourglass",
  "image",
  "import",
  "important",
  "inbox",
  "info",
  "key",
  "keyboard",
  "laptop",
  "layers",
  "lightbulbt",
  "light-theme",
  "line-chart",
  "link",
  "link-remove",
  "list-check",
  "location",
  "location-map",
  "lock-on",
  "lock-off",
  "map",
  "map-signs",
  "menu",
  "menuOpen",
  "minus",
  "minus-check",
  "minus-c",
  "minus-square",
  "minus-s-check",
  "money",
  "move-down",
  "move-up",
  "news",
  "not-edit",
  "note",
  "notebook",
  "notepad",
  "number-field",
  "number-list",
  "mark",
  "open-folder",
  "paste",
  "pause",
  "pause-c",
  "pause-filled",
  "percent",
  "pie-chart",
  "paper-clip",
  "phone",
  "phone-dev",
  "phone-desktop",
  "pin",
  "play-c",
  "play",
  "play-filled",
  "plus",
  "plus-c",
  "plus-square",
  "plus-s-check",
  "plus-s-double",
  "plus-s-double-check",
  "pointer",
  "power",
  "print",
  "qcode",
  "help-circle",
  "question",
  "radio-on",
  "region",
  "refresh",
  "repeat",
  "reply",
  "rub",
  "save",
  "search",
  "search-check",
  "search-in",
  "search-out",
  "select",
  "send",
  "separator",
  "sertificat",
  "server",
  "settings",
  "settings-dev",
  "share",
  "sign-out",
  "sign-up",
  "scale-fit",
  "slider",
  "sort-down",
  "sort-check",
  "sort-up",
  "speed",
  "spinner",
  "star",
  "star-fill",
  "status",
  "step",
  "steps",
  "stop-c",
  "stop-filled",
  "switcher",
  "sync",
  "system-settings",
  "square",
  "tab",
  "table",
  "table-pivot",
  "table-pivot-check",
  "table-column",
  "table-rows",
  "table-set-v",
  "tablet",
  "tag",
  "tags",
  "tap",
  "target",
  "tasks",
  "text",
  "textarea",
  "text-color",
  "text-field",
  "text-field-mask",
  "timer",
  "toolbox",
  "tools",
  "try",
  "undo",
  "ungroup",
  "up",
  "upload",
  "usd",
  "user",
  "users",
  "user-add",
  "user-delete",
  "video-camera",
  "video-square",
  "warning-c",
  "warning",
  "wifi"
];

export function Playground() {
  return (
    <section className="example">
      <h3 className="ex-title">Header</h3>
      <br />
      <div className="tpl-grid tpl-grid_s-ratio_1-1-1-1-1 tpl-grid_row-gap_full">
        {header.map((name) => (
          <IconsItem icon={name} {...defaultKnobs()}/>
        ))}
      </div>

      <h3 className="ex-title">Functional Bar</h3>
      <br />
      <div className="tpl-grid tpl-grid_s-ratio_1-1-1-1-1 tpl-grid_row-gap_full">
        {functionalBar.map((name) => (
          <IconsItem icon={name} {...defaultKnobs()}/>
        ))}
      </div>

      <h3 className="ex-title">Diagram</h3>
      <br />
      <div className="tpl-grid tpl-grid_s-ratio_1-1-1-1-1 tpl-grid_row-gap_full">
        {diagrams.map((name) => (
          <IconsItem icon={name} {...defaultKnobs()}/>
        ))}
      </div>

      <h3 className="ex-title">Arrows</h3>
      <br />
      <div className="tpl-grid tpl-grid_s-ratio_1-1-1-1-1 tpl-grid_row-gap_full">
        {arrows.map((name) => (
          <IconsItem icon={name} {...defaultKnobs()}/>
        ))}
      </div>

      <h3 className="ex-title">All icons</h3>
      <br />
      <div className="tpl-grid tpl-grid_s-ratio_1-1-1-1-1 tpl-grid_row-gap_full">
        {allIcons.map((name) => (
          <IconsItem icon={name} {...defaultKnobs()}/>
        ))}
      </div>

    </section>
  );
}

export default createMetadata({
  title: 'Компоненты|/Графика/Icons',
  id: 'components/Icons',
  parameters: {
    docs: {
      page: mdx,
    },
    design: {
      type: 'figma',
      url: 'https://www.figma.com/file/SLc0YGhuDotve6MTCBHlGxDU/Consta-Graphics?node-id=0%3A1',
    },
  },
});
